apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  params:
  - name: username
    type: string
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"     
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: goodbye
spec:
  params:
  - name: username
    type: string
  tasks:
    - name: goodbye
      taskRef:
        name: goodbye
      params:
      - name: username
        value: $(params.username)
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: goodbye-run
  labels:
    'backstage.io/kubernetes-id': dice-roller
spec:
  pipelineRef:
    name: goodbye
  params:
  - name: username
    value: "Tekton"
